name: Auto Publish JQL.Net

on:
  release:
    types: [published] # Triggers saat Anda klik "Publish Release" di GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore & Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack with Dynamic Version
      run: |
        # Mengambil nama tag (misal v1.0.5) dan membuang huruf 'v'-nya
        VERSION=${GITHUB_REF_NAME#v}
        dotnet pack --configuration Release --no-build -o dist /p:PackageVersion=$VERSION

    - name: Push to NuGet
      run: dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.nupkg
        generate_release_notes: true